# http://0.0.0.0:9000/login in your browser -> username=minio and password=minio@2022
    # Url Public file
    # http://0.0.0.0:9001/bucket-name/roshandelpoor.jpeg

version: '3'
services:
  minio:
    container_name: server_minio
    image: minio/minio:RELEASE.2021-12-29T06-49-06Z.fips
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio #MINIO_ACCESS_KEY
      MINIO_ROOT_PASSWORD: minio@2022 #MINIO_SECRET_KEY
    volumes:
      - ./storage:/data
    command: server --address 0.0.0.0:9001 --console-address 0.0.0.0:9000 /data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3




